name: "Setup Node.js and it's dependencies"
description: "This action sets up Node.js and it's dependencies for the workflow"
runs:
  using: "composite"
  steps:
    - name: Clone the repository
      uses: actions/checkout@v4
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with: 
        path: node_modules
        key: runner-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash