name: "Deploy Application"
on: [push]
jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Test code
        uses: actions/checkout@v6 
        with:
          path: myfolder
      - name: List files
        run: ls -la myfolder
      - name: Install dependencies
        run: npm install
        working-directory: myfolder
      - name: Running Tests
        run: npx vitest run src/App.test.jsx
        working-directory: myfolder
  build: 
    needs: checkout_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
            path: myfolder
      - name: Install dependencies
        run: npm install
        working-directory: myfolder
      - name: Building the application
        run: npm run build
        working-directory: myfolder