name: "Deploy Application"
on: [push]
jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Test code
        uses: actions/checkout@v6 
      - name: Install dependencies
        run: npm install
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: runner-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      -  name: Install dependencies
         if: steps.cache-node-modules.outputs.cache-hit != 'true'
         run: npm install
      - name: Running Tests
        run: npx test
  build: 
    needs: checkout_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: runner-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'   
        run: npm install
        
      - name: Building the application
        run: npm run build
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
       
            
      - name: Install dependencies
        run: npm install
      

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Deploying the application
        run: echo "Deploying the application..."