name: "Deploy Application"
on: 
    push:
        branches: [main]
        paths-ignore:
            - ".github/workflows/**"
    workflow_dispatch:
jobs:
  checkout_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: ./.github/action/setupnode
      - name: Run tests
        run: npm test
  build:
    needs: checkout_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: ./.github/action/setupnode
      - name: Building the application
        run: npm run build
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and install dependencies
        uses: ./.github/action/setupnode
      - name: Deploying the application
        run: npm run deploy